import type{Item,SpatialPiece,RuleItem,MemoryItem,ControlItem,SpatialItem,AudioItem,SocialItem,NaturalisticItem,MetaItem,MathItem,VerbalItem}from'./types';
export type AuditResult={ok:boolean;checks:string[];warnings:string[]};
export const spatialKey=(ps:SpatialPiece[])=>ps.map(p=>`${p.x},${p.y},${p.size},${p.rotation},${p.kind}`).sort().join('|');
export function transformSpatial(base:SpatialPiece[],rot:number,mirror:boolean){return base.map(p=>{let x=p.x,y=p.y;if(mirror)x=2-x;for(let i=0;i<rot/90;i++){const nx=2-y;y=x;x=nx}return{...p,x,y,rotation:(p.rotation+(mirror?-1:1)*rot+360)%360}})}
function fourChoices(x:{choices:string[];correct:number}){return x.choices.length===4&&new Set(x.choices).size===4&&x.correct>=0&&x.correct<4}
function auditRule(x:RuleItem,checks:string[],warnings:string[]){const s=x.sequence,base=x.ruleParams.a;const sh=['●','■','▲','◆','★','⬢'];const at=(i:number)=>sh[(base+i+120)%6];let expected='';switch(x.ruleParams.kind){case'alternance':expected=s[1];break;case'progression':expected=at(s.length*(x.ruleParams.b||1));break;case'cycle3':expected=s[0];break;case'cycle4':expected=s[3];break;case'composed':expected=s[1];break;case'double':expected=s[2];break;case'conditional':expected=s[0];break;case'mirror':expected=s[s.length-3];break;case'jump':expected=at(s.length*(x.ruleParams.b||2));break;case'doubleCycle':expected=s[0];break;default:expected=''}const ok=x.ruleParams.kind.startsWith('bank:') ? !!x.choices[x.correct] : !!expected&&x.choices[x.correct]===expected;checks.push(`rule semantics:${ok?'PASS':'FAIL'}`);if(new Set(s).size<3)warnings.push('rule visual variety is limited');return ok}
function auditMemory(x:MemoryItem,checks:string[]){const ok=x.choices[x.correct]===x.target&&x.target.length>0&&x.encodeMs>=1000&&x.hideMs>=300&&x.sequence.length>=4;checks.push(`memory target:${ok?'PASS':'FAIL'}`);return ok}
function auditSpatial(x:SpatialItem,checks:string[]){let expected=transformSpatial(x.pieces,x.transform.rotation,x.transform.mirror);if(x.spatialMode==='double-transform')expected=transformSpatial(expected,x.transform.rotation2||0,x.transform.mirror2||false);else if(x.spatialMode==='opposite-turn')expected=transformSpatial(x.pieces,(360-x.transform.rotation)%360,false);const ok=spatialKey(x.choices[x.correct])===spatialKey(expected)&&new Set(x.choices.map(spatialKey)).size===4;checks.push(`spatial transform:${ok?'PASS':'FAIL'}`);if(x.pieces.length<2) return false;return ok}
function auditControl(x:ControlItem,checks:string[]){const n=x.trials.length,switches=x.trials.filter(t=>t.switchAt).length;let semantic=true;for(let i=0;i<n;i++){const t=x.trials[i];let expected:boolean;if(x.controlMode==='go-nogo')expected=t.target==='circle';else if(x.controlMode==='reverse')expected=t.target==='triangle';else if(x.controlMode==='switch')expected=i<Math.floor(n/2)?t.target==='circle':t.target==='triangle';else expected=i<Math.floor(n/2)?t.target==='circle':i<Math.floor(n*.75)?t.target==='triangle':t.target==='circle';if(t.go!==expected)semantic=false}const go=x.trials.filter(t=>t.go).length,nogo=n-go,balanced=go>=Math.floor(n*.35)&&nogo>=Math.floor(n*.35);const expectedSwitches=x.controlMode==='switch'?1:x.controlMode==='double-switch'?2:0;const ok=n>=18&&switches===expectedSwitches&&semantic&&balanced;checks.push(`control semantics:${ok?'PASS':'FAIL'}`);return ok}
function auditAudio(x:AudioItem,checks:string[]){const ids=x.choiceRhythms.map(r=>r.join(''));const target=x.rhythm.join('');const ok=x.rhythm.length>=8&&x.rhythm.every(n=>n===0||n===1)&&x.choiceRhythms.length===4&&x.choiceRhythms.every(r=>r.length===x.rhythm.length)&&new Set(ids).size===4&&ids[x.correct]===target&&x.tempoMs>=280;checks.push(`audio rhythm semantics:${ok?'PASS':'FAIL'}`);return ok}
function auditSocial(x:SocialItem,checks:string[]){const ok=x.bank?x.scene.answer===x.choices[x.correct]&&x.prompt.length>12&&x.scene.cue.length>5:x.scene.answer===x.choices[x.correct]&&x.scene.belief.length>12&&x.scene.reality.length>12&&x.scene.question.length>12&&x.scene.cue.length>5;checks.push(`social semantics:${ok?'PASS':'FAIL'}`);return ok}
function auditNatural(x:NaturalisticItem,checks:string[],warnings:string[]=[]){const ok=x.sequence.length>=5&&x.rule.length===x.sequence.length+1&&fourChoices(x)&&x.correct>=0&&x.correct<4&&x.natureMode&&x.choices[x.correct].length>0;checks.push(`naturalistic semantics:${ok?'PASS':'FAIL'}`);if(x.sequence.every(v=>v===x.sequence[0]))warnings.push('naturalistic sequence has no variation');return ok}
function auditMeta(x:MetaItem,checks:string[]){if(x.bank){const ok=x.choices[x.correct].length>0&&x.prompt.length>12&&x.confidenceOptions.length===3;checks.push(`meta bank semantics:${ok?'PASS':'FAIL'}`);return ok}const a=x.metaSpec;let expected=a.correct?'A est plus grand':'B est plus grand';if(a.kind==='ratio')expected=a.correct?'A est plus grand':'B est plus grand';const ok=x.choices[x.correct]===expected&&x.confidenceOptions.length===3&&x.confidenceCorrect>=0&&x.confidenceCorrect<=2;checks.push(`meta semantics:${ok?'PASS':'FAIL'}`);return ok}
function auditMath(x:MathItem,checks:string[]){const s=x.mathSpec;let expected:number;if(s.kind==='sequence')expected=s.a+4*s.b;else if(s.kind==='boxes')expected=(s.c-s.b)/2;else if(s.kind==='cumulative')expected=s.b*s.c;else if(s.kind==='constraint')expected=s.b+s.c;else if(s.kind==='difference')expected=s.b;else if(s.kind==='bank'){const answerText=s.answerText||String(s.answer);const ok=x.choices[x.correct]===answerText;checks.push(`math bank semantics:${ok?'PASS':'FAIL'}`);return ok}else expected=(s.a+s.b+s.c)/3;const ok=expected===s.answer&&x.choices[x.correct]===String(expected)&&Number.isFinite(expected);checks.push(`math semantics:${ok?'PASS':'FAIL'}`);return ok}
function auditVerbal(x:VerbalItem,checks:string[]){const ok=x.choices[x.correct]===x.relation.right2&&Object.values(x.relation).every(v=>typeof v==='string'&&v.length>1);checks.push(`verbal semantics:${ok?'PASS':'FAIL'}`);return ok}
export function auditItem(item:Item):AuditResult{const checks:string[]=[];const warnings:string[]=[];let ok=item.family==='CONTROL'?item.trials.length>=18:item.family==='SPATIAL'?item.choices.length===4&&new Set(item.choices.map(spatialKey)).size===4:fourChoices(item);checks.push(`structure:${ok?'PASS':'FAIL'}`);if(item.family==='RULE')ok=auditRule(item,checks,warnings)&&ok;if(item.family==='MEMORY')ok=auditMemory(item,checks)&&ok;if(item.family==='SPATIAL')ok=auditSpatial(item,checks)&&ok;if(item.family==='CONTROL')ok=auditControl(item,checks)&&ok;if(item.family==='AUDIO')ok=auditAudio(item,checks)&&ok;if(item.family==='SOCIAL')ok=auditSocial(item,checks)&&ok;if(item.family==='NATURALISTIC')ok=auditNatural(item,checks)&&ok;if(item.family==='META')ok=auditMeta(item,checks)&&ok;if(item.family==='MATH')ok=auditMath(item,checks)&&ok;if(item.family==='VERBAL')ok=auditVerbal(item,checks)&&ok;return{ok,checks,warnings}}
